title: Linxuan Li's Homepage
page-top-title: Linxuan Li
top-section-bg-text: Thermal Energy Engineering
home-subtitle: Linxuan Li&ensp;|&ensp; 李林宣
copyright-text: '&copy; Linxuan Li 2024-2025. All Rights Reserved.'
